// Code generated by Kitex v0.6.1. DO NOT EDIT.

package additionmanagement

import (
	"context"
	management "github.com/ararchch/api-gateway/kitex-rpc-server/kitex_gen/addition/management"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return additionManagementServiceInfo
}

var additionManagementServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AdditionManagement"
	handlerType := (*management.AdditionManagement)(nil)
	methods := map[string]kitex.MethodInfo{
		"addNumbers": kitex.NewMethodInfo(addNumbersHandler, newAdditionManagementAddNumbersArgs, newAdditionManagementAddNumbersResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "management",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func addNumbersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*management.AdditionManagementAddNumbersArgs)
	realResult := result.(*management.AdditionManagementAddNumbersResult)
	success, err := handler.(management.AdditionManagement).AddNumbers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdditionManagementAddNumbersArgs() interface{} {
	return management.NewAdditionManagementAddNumbersArgs()
}

func newAdditionManagementAddNumbersResult() interface{} {
	return management.NewAdditionManagementAddNumbersResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddNumbers(ctx context.Context, req *management.AdditionRequest) (r *management.AdditionResponse, err error) {
	var _args management.AdditionManagementAddNumbersArgs
	_args.Req = req
	var _result management.AdditionManagementAddNumbersResult
	if err = p.c.Call(ctx, "addNumbers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
