// Code generated by hertz generator.

package handler

import (
	"context"
	"encoding/json"
	"fmt"

	//"encoding/json"

	"github.com/cloudwego/hertz/pkg/app"
	//"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	gatewayUtils "github.com/ararchch/api-gateway/utils"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {

	service := c.Param("service")
	method := c.Param("method")

	kitexClient, err := gatewayUtils.GenerateClient(service)
	if (err != nil) {
		fmt.Println("could not locate service")
		panic(err)
	}

	resp, err := gatewayUtils.MakeRpcRequest2(ctx, kitexClient, method, string(c.Request.Body()))
	if (err != nil){
		fmt.Println("RPC request error")
		panic(err)
	}

	var obj interface{}
	json.Unmarshal([]byte(resp.(string)), &obj)

	c.JSON(consts.StatusOK, obj)
}
