// Code generated by hertz generator.

package main

import (
	handler "github.com/ararchch/api-gateway/hertz-http-server/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.POST("/:service/:method", handler.Ping)

	// your code ...
}
