// Code generated by hertz generator.

package api

import (
	"context"

	api "github.com/ararchch/api-gateway/hertz-http-server/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// AddNumbers .
// @router /add [POST]
func AddNumbers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AdditionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AdditionResponse)

	c.JSON(consts.StatusOK, resp)
}
